package View;/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import DB.PersisteTreino;

/**
 *
 * @author user
 */
public class AddTreino extends javax.swing.JFrame {

    /**
     * Creates new form AddTreino
     */
    public AddTreino() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        textNomeTreino = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        textTipoTreino = new javax.swing.JTextField();
        buttonVoltarTreino = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        buttonSalvarTreino = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        textObsTreino = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        comboBoxDivisaoTreino = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        textTempDescansoTreino = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextDescrisaoTreino = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        textNomeTreino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNomeTreinoActionPerformed(evt);
            }
        });

        jLabel13.setText("Nome da unidade");

        textTipoTreino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textTipoTreinoActionPerformed(evt);
            }
        });

        buttonVoltarTreino.setText("voltar");
        buttonVoltarTreino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonVoltarTreinoActionPerformed(evt);
            }
        });

        jLabel10.setText("obigetivos/tipo:");

        buttonSalvarTreino.setText("salvar");
        buttonSalvarTreino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSalvarTreinoActionPerformed(evt);
            }
        });

        jLabel11.setText("Descrisao:");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Novo treino");

        jLabel12.setText("OBS:");

        textObsTreino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textObsTreinoActionPerformed(evt);
            }
        });

        jLabel5.setText("Divisao");

        comboBoxDivisaoTreino.setEditable(true);
        comboBoxDivisaoTreino.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A,B", "A,B,C", "A,B,C,D", "A,B,C,D,E", "SEMANAL", "PERSONALIZADO" }));
        comboBoxDivisaoTreino.setToolTipText("");
        comboBoxDivisaoTreino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxDivisaoTreinoActionPerformed(evt);
            }
        });

        jLabel14.setText("Tempo de descanso");

        textTempDescansoTreino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textTempDescansoTreinoActionPerformed(evt);
            }
        });

        TextDescrisaoTreino.setAlignmentX(0.0F);
        TextDescrisaoTreino.setAutoscrolls(false);
        jScrollPane1.setViewportView(TextDescrisaoTreino);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(buttonVoltarTreino)
                                                .addGap(63, 63, 63)
                                                .addComponent(jLabel1)
                                                .addGap(0, 159, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                .addComponent(jLabel12)
                                                                .addComponent(jLabel10)
                                                                .addComponent(textTipoTreino, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                                                                .addComponent(jLabel13)
                                                                .addComponent(textNomeTreino, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                                                                .addGroup(layout.createSequentialGroup()
                                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(comboBoxDivisaoTreino, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(jLabel5))
                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(jLabel14)
                                                                                .addComponent(textTempDescansoTreino)))
                                                                .addComponent(jLabel11)
                                                                .addComponent(textObsTreino)))
                                                .addGap(44, 44, 44)
                                                .addComponent(buttonSalvarTreino)))
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1)
                                        .addComponent(buttonVoltarTreino))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textNomeTreino, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textTipoTreino, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(comboBoxDivisaoTreino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(textTempDescansoTreino, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textObsTreino, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(buttonSalvarTreino)
                                .addContainerGap())
        );

        pack();
    }// </editor-fold>

    private void textNomeTreinoActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void textTipoTreinoActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void buttonVoltarTreinoActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        //botao voltar
        //açao
    }

    private void textObsTreinoActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void comboBoxDivisaoTreinoActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void textTempDescansoTreinoActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void buttonSalvarTreinoActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        //botao salvar
        //açao
        String nomeTreino = textNomeTreino.getText();
        String tipoTreino = textTipoTreino.getText();
        Object divisaoTreino = comboBoxDivisaoTreino.getSelectedItem();
        String tempDescanso = textTempDescansoTreino.getText();
        String descrisaoTreino = TextDescrisaoTreino.getText();
        String odsTreino = textObsTreino.getText();

        String treinoFull = "{" +
                "\"nomeTreino\": \"" + nomeTreino + "\"," +
                "\"tipoTreino\": \"" + tipoTreino + "\"," +
                "\"divisaoTreino\": \"" + divisaoTreino + "\"," +
                "\"tempDescanso\": \"" + tempDescanso + "\"," +
                "\"descricaoTreino\": \"" + descrisaoTreino + "\"," +
                "\"obsTreino\": \"" + odsTreino + "\"" +
        "}";

        System.out.println(treinoFull);

        System.out.println();

        PersisteTreino persisteTreino = new PersisteTreino();

        persisteTreino.salvarEmArquivo("testeEdit.odt", treinoFull);


    }



    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddTreino.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddTreino.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddTreino.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddTreino.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddTreino().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JTextPane TextDescrisaoTreino;
    private javax.swing.JButton buttonSalvarTreino;
    private javax.swing.JButton buttonVoltarTreino;
    private javax.swing.JComboBox<String> comboBoxDivisaoTreino;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField textNomeTreino;
    private javax.swing.JTextField textObsTreino;
    private javax.swing.JTextField textTempDescansoTreino;
    private javax.swing.JTextField textTipoTreino;
    // End of variables declaration
}