package View;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;

/**
 *
 * @author user
 */
public class Inicial extends javax.swing.JFrame {

    /**
     * Creates new form inicial
     */
    public Inicial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        textPumpGym = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jCheckBox_Masculino = new javax.swing.JCheckBox();
        jCheckBox_Feminino = new javax.swing.JCheckBox();
        jCheckBox_platina = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        txt_filtros = new javax.swing.JLabel();
        jLabel_sexo = new javax.swing.JLabel();
        jLabel_planos = new javax.swing.JLabel();
        jCheckBox_gold = new javax.swing.JCheckBox();
        jCheckBox_familia = new javax.swing.JCheckBox();
        jButton_besquisar = new javax.swing.JButton();
        buscador_01 = new javax.swing.JTextField();
        jButton_buscar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        DefaultTableModel tableModel = new DefaultTableModel();
        tableinicial = new javax.swing.JTable(tableModel);
        jMenuBar1 = new javax.swing.JMenuBar();
        addAluno = new javax.swing.JMenu();
        jMenuItem_addAluno = new javax.swing.JMenuItem();
        jMenuItem_addProfesor = new javax.swing.JMenuItem();
        jMenuItem_addUnidade = new javax.swing.JMenuItem();
        jMenuItem_addTrino = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));
        setName("buscar"); // NOI18N

        textPumpGym.setFont(new java.awt.Font("Stencil", 1, 48)); // NOI18N
        textPumpGym.setText("PumpGym");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jCheckBox_Masculino.setText("Masculino");
        jCheckBox_Masculino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_MasculinoActionPerformed(evt);
            }
        });

        jCheckBox_Feminino.setText("Feminino");

        jCheckBox_platina.setText("platina");
        jCheckBox_platina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_platinaActionPerformed(evt);
            }
        });

        txt_filtros.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        txt_filtros.setText("Filtros");

        jLabel_sexo.setText("sexo:");

        jLabel_planos.setText("planos");

        jCheckBox_gold.setText("gold");
        jCheckBox_gold.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_goldActionPerformed(evt);
            }
        });

        jCheckBox_familia.setText("familia");
        jCheckBox_familia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_familiaActionPerformed(evt);
            }
        });

        jButton_besquisar.setBackground(new java.awt.Color(153, 153, 153));
        jButton_besquisar.setText("pesquisar");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(jButton_besquisar))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addComponent(jLabel3)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(txt_filtros)
                                                                        .addComponent(jCheckBox_Masculino)
                                                                        .addComponent(jCheckBox_Feminino)
                                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                                .addGap(6, 6, 6)
                                                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addComponent(jCheckBox_platina)
                                                                                        .addComponent(jCheckBox_gold)
                                                                                        .addComponent(jCheckBox_familia)))))
                                                        .addComponent(jLabel_sexo)
                                                        .addComponent(jLabel_planos))
                                                .addGap(0, 66, Short.MAX_VALUE)))
                                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(txt_filtros)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel_sexo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox_Masculino)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox_Feminino)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel_planos)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(38, 38, 38)
                                                .addComponent(jLabel3))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jCheckBox_platina)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jCheckBox_gold)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox_familia)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton_besquisar)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        buscador_01.setToolTipText("");
        buscador_01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscador_01ActionPerformed(evt);
            }
        });

        jButton_buscar.setBackground(new java.awt.Color(153, 153, 153));
        jButton_buscar.setText("buscar");
        jButton_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_buscarActionPerformed(evt);
            }
        });

        tableinicial.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                        {null, null, null, null, null},
                        {null, null, null, null, null},
                        {null, null, null, null, null},
                        {null, null, null, null, null}
                },
                new String [] {
                        "Nome", "CPF", "Data Nascimento", "Sexo"
                }
        ) {
            Class[] types = new Class [] {
                    java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tableinicial.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tableinicialAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane2.setViewportView(tableinicial);

        jMenuBar1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jMenuBar1AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        addAluno.setText("menu");

        jMenuItem_addAluno.setAccelerator(addAluno.getAccelerator());
        jMenuItem_addAluno.setText("add Aluno");
        jMenuItem_addAluno.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jMenuItem_addAlunoAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
                jMenuItem_addAlunoAncestorMoved(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jMenuItem_addAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_addAlunoActionPerformed(evt);
            }
        });
        addAluno.add(jMenuItem_addAluno);

        jMenuItem_addProfesor.setText("add Professor");
        jMenuItem_addProfesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_addProfesorActionPerformed(evt);
            }
        });
        addAluno.add(jMenuItem_addProfesor);

        jMenuItem_addUnidade.setText("add Unidade");
        jMenuItem_addUnidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_addUnidadeActionPerformed(evt);
            }
        });
        addAluno.add(jMenuItem_addUnidade);

        jMenuItem_addTrino.setText("add Treino");
        jMenuItem_addTrino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_addTrinoActionPerformed(evt);
            }
        });
        addAluno.add(jMenuItem_addTrino);



        jMenuBar1.add(addAluno);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(textPumpGym)
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(buscador_01, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jButton_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 796, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(16, 16, 16))))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(textPumpGym)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(buscador_01, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jButton_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>

    private void jCheckBox_MasculinoActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void jCheckBox_platinaActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void buscador_01ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void jButton_buscarActionPerformed(java.awt.event.ActionEvent evt) {

        ObjectMapper objectMapper = new ObjectMapper();

        String caminhoArquivo = "/Users/miguelmoura/Desktop/TESTE/testeEdit.odt";

        try {
            // Abre o arquivo para leitura usando FileReader
            FileReader fileReader = new FileReader(caminhoArquivo);

            // Cria um BufferedReader para ler linhas de texto eficientemente
            BufferedReader bufferedReader = new BufferedReader(fileReader);

            // Lê cada linha do arquivo e imprime no console
            String linha;
            while ((linha = bufferedReader.readLine()) != null) {
                try {
                    // Converter a string JSON para um objeto JsonNode
                    JsonNode linhaJSON = objectMapper.readTree(linha);


                    Object[] novaLinha = new JsonNode[]{linhaJSON};
                    ((DefaultTableModel)  tableinicial.getModel()).addRow(novaLinha);



                } catch (Exception e) {
                    e.printStackTrace();
                }
            }

            // Fecha o BufferedReader e o FileReader
            bufferedReader.close();
            fileReader.close();
        } catch (IOException e) {
            // Trata exceções de leitura de arquivo
            e.printStackTrace();
        }

//        Object[] novaLinha = {"Novo Dado 1", "Novo Dado 2", "Novo Dado 3"};
//        ((DefaultTableModel)  tableinicial.getModel()).addRow(novaLinha);
    }

    private void jCheckBox_familiaActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void jCheckBox_goldActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void jMenuBar1AncestorAdded(javax.swing.event.AncestorEvent evt) {
        // TODO add your handling code here:
    }


    private void jMenuItem_addAlunoAncestorAdded(javax.swing.event.AncestorEvent evt) {
        // TODO add your handling code here:
    }

    private void jMenuItem_addAlunoAncestorMoved(javax.swing.event.AncestorEvent evt) {
        // TODO add your handling code here:
    }

    private void jMenuItem_addAlunoActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        AddAlunos novoaluon = new AddAlunos();
        novoaluon.setVisible(true);
    }

    private void jMenuItem_addProfesorActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        AddProfessores novoProfessor = new AddProfessores();
        novoProfessor.setVisible(true);

    }

    private void jMenuItem_addUnidadeActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        AddUnidades novoUnidade = new AddUnidades();
        novoUnidade.setVisible(true);
    }

    private void jMenuItem_addTrinoActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        AddTreino novoTreino = new AddTreino();
        novoTreino.setVisible(true);

    }

    private void tableinicialAncestorAdded(javax.swing.event.AncestorEvent evt) {
        // TODO add your handling code here:
        //added

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JMenu addAluno;
    private javax.swing.JTextField buscador_01;
    private javax.swing.JButton jButton_besquisar;
    private javax.swing.JButton jButton_buscar;
    private javax.swing.JCheckBox jCheckBox_Feminino;
    private javax.swing.JCheckBox jCheckBox_Masculino;
    private javax.swing.JCheckBox jCheckBox_familia;
    private javax.swing.JCheckBox jCheckBox_gold;
    private javax.swing.JCheckBox jCheckBox_platina;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel_planos;
    private javax.swing.JLabel jLabel_sexo;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem_addAluno;
    private javax.swing.JMenuItem jMenuItem_addProfesor;
    private javax.swing.JMenuItem jMenuItem_addTrino;
    private javax.swing.JMenuItem jMenuItem_addUnidade;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tableinicial;
    private javax.swing.JLabel textPumpGym;
    private javax.swing.JLabel txt_filtros;
    // End of variables declaration
}